# Generated by Django 3.2.25 on 2025-05-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('notifications', '0002_auto_20250503_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='userId',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user'),
        ),
    ]
