# Generated by Django 3.2.25 on 2025-05-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_archivage',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
