# Generated by Django 3.2.25 on 2025-05-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_date_archivage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstoprojects',
            name='skills',
            field=models.CharField(default='', max_length=30),
        ),
    ]
