# Generated by Django 3.2.25 on 2025-05-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sprint_duration', models.IntegerField(default=2)),
                ('sprint_start', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('is_ai_enabled', models.BooleanField(default=False)),
                ('github_integration_id', models.IntegerField(blank=True, null=True)),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archives',
            },
        ),
    ]
