# Generated by Django 3.2.25 on 2025-06-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20250614_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='user',
        ),
    ]
