# Generated by Django 3.2.25 on 2025-05-05 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprintId',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.sprint'),
        ),
    ]
