# Generated by Django 3.2.25 on 2025-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0002_alter_task_sprintid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subTask',
            field=models.TextField(blank=True, default=''),
        ),
    ]
