# Generated by Django 3.2.25 on 2025-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0003_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subTask',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
