//import type { Project } from "~/schema.ts"

export const mockProject = {
  id: "proj-123",
  name: "Refonte du site e-commerce",
  description:
    "Modernisation complète de la plateforme e-commerce avec amélioration de l'expérience utilisateur et optimisation des performances.",
  startDate: "2023-09-01",
  sprintDuration: 14,
  archived: false,
  sprints: [
    {
      id: "sprint-1",
      number: 1,
      startDate: "2023-09-01",
      endDate: "2023-09-14",
    },
    {
      id: "sprint-2",
      number: 2,
      startDate: "2023-09-15",
      endDate: "2023-09-28",
    },
    {
      id: "sprint-3",
      number: 3,
      startDate: "2023-09-29",
      endDate: "2023-10-12",
    },
    {
      id: "sprint-4",
      number: 4,
      startDate: "2023-10-13",
      endDate: "2023-10-26",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Analyse des besoins utilisateurs",
      description: "Réaliser des entretiens avec les utilisateurs et analyser les données d'utilisation actuelles",
      status: "completed",
      assignee: "Sophie Martin",
      sprintId: "sprint-1",
      subTasks: [
        {
          id: "subtask-1-1",
          title: "Préparation des questionnaires",
          description: "Élaborer les questions pour les entretiens utilisateurs",
          status: "completed",
          assignee: "Sophie Martin",
        },
        {
          id: "subtask-1-2",
          title: "Conduite des entretiens",
          description: "Réaliser 10 entretiens avec des utilisateurs clés",
          status: "completed",
          assignee: "Thomas Dubois",
        },
        {
          id: "subtask-1-3",
          title: "Analyse des résultats",
          description: "Compiler et analyser les données recueillies",
          status: "completed",
          assignee: "Sophie Martin",
        },
      ],
    },
    {
      id: "task-2",
      title: "Conception de l'interface utilisateur",
      description: "Créer les wireframes et maquettes pour la nouvelle interface",
      status: "completed",
      assignee: "Lucas Bernard",
      sprintId: "sprint-1",
      subTasks: [
        {
          id: "subtask-2-1",
          title: "Wireframes basse fidélité",
          description: "Créer les wireframes pour les principales pages",
          status: "completed",
          assignee: "Lucas Bernard",
        },
        {
          id: "subtask-2-2",
          title: "Maquettes haute fidélité",
          description: "Concevoir les maquettes détaillées avec la charte graphique",
          status: "completed",
          assignee: "Lucas Bernard",
        },
      ],
    },
    {
      id: "task-3",
      title: "Développement frontend",
      description: "Implémenter l'interface utilisateur avec React et Next.js",
      status: "in-progress",
      assignee: "Emma Petit",
      sprintId: "sprint-2",
      subTasks: [
        {
          id: "subtask-3-1",
          title: "Mise en place de l'architecture",
          description: "Configurer le projet Next.js et les dépendances",
          status: "completed",
          assignee: "Emma Petit",
        },
        {
          id: "subtask-3-2",
          title: "Développement des composants UI",
          description: "Créer les composants réutilisables selon la maquette",
          status: "in-progress",
          assignee: "Emma Petit",
        },
        {
          id: "subtask-3-3",
          title: "Intégration des pages",
          description: "Assembler les composants pour créer les pages complètes",
          status: "todo",
          assignee: "Emma Petit",
        },
      ],
    },
    {
      id: "task-4",
      title: "Développement backend",
      description: "Créer les API et services nécessaires pour le frontend",
      status: "in-progress",
      assignee: "Alexandre Dupont",
      sprintId: "sprint-2",
      subTasks: [
        {
          id: "subtask-4-1",
          title: "Conception de la base de données",
          description: "Définir le schéma de la base de données",
          status: "completed",
          assignee: "Alexandre Dupont",
        },
        {
          id: "subtask-4-2",
          title: "Développement des API REST",
          description: "Implémenter les endpoints pour les fonctionnalités principales",
          status: "in-progress",
          assignee: "Alexandre Dupont",
        },
      ],
    },
    {
      id: "task-5",
      title: "Tests et assurance qualité",
      description: "Réaliser les tests unitaires, d'intégration et fonctionnels",
      status: "todo",
      assignee: "Julie Moreau",
      sprintId: "sprint-3",
      subTasks: [
        {
          id: "subtask-5-1",
          title: "Mise en place de l'environnement de test",
          description: "Configurer les outils de test automatisés",
          status: "todo",
          assignee: "Julie Moreau",
        },
        {
          id: "subtask-5-2",
          title: "Rédaction des tests unitaires",
          description: "Écrire les tests pour les composants et services",
          status: "todo",
          assignee: "Julie Moreau",
        },
      ],
    },
    {
      id: "task-6",
      title: "Optimisation des performances",
      description: "Améliorer les temps de chargement et l'expérience utilisateur",
      status: "todo",
      assignee: "Nicolas Leroy",
      sprintId: "sprint-3",
      subTasks: [
        {
          id: "subtask-6-1",
          title: "Audit de performance",
          description: "Analyser les performances actuelles et identifier les points d'amélioration",
          status: "todo",
          assignee: "Nicolas Leroy",
        },
        {
          id: "subtask-6-2",
          title: "Optimisation des images et assets",
          description: "Réduire la taille des ressources et implémenter le lazy loading",
          status: "todo",
          assignee: "Nicolas Leroy",
        },
      ],
    },
    {
      id: "task-7",
      title: "Déploiement et mise en production",
      description: "Préparer et exécuter le déploiement de la nouvelle version",
      status: "todo",
      assignee: "Alexandre Dupont",
      sprintId: "sprint-4",
      subTasks: [
        {
          id: "subtask-7-1",
          title: "Configuration de l'environnement de production",
          description: "Préparer les serveurs et services cloud",
          status: "todo",
          assignee: "Alexandre Dupont",
        },
        {
          id: "subtask-7-2",
          title: "Plan de migration des données",
          description: "Élaborer la stratégie de migration des données existantes",
          status: "todo",
          assignee: "Alexandre Dupont",
        },
      ],
    },
    {
      id: "task-8",
      title: "Formation et documentation",
      description: "Préparer la documentation technique et former les équipes",
      status: "todo",
      assignee: "Sophie Martin",
      sprintId: "sprint-4",
      subTasks: [
        {
          id: "subtask-8-1",
          title: "Rédaction de la documentation technique",
          description: "Documenter l'architecture et les composants du système",
          status: "todo",
          assignee: "Sophie Martin",
        },
        {
          id: "subtask-8-2",
          title: "Préparation des sessions de formation",
          description: "Créer les supports de formation pour les équipes internes",
          status: "todo",
          assignee: "Sophie Martin",
        },
      ],
    },
  ],
}
