import type { Project, User } from "./types"

// Utilisateurs mockés
export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Thomas Dubois",
    email: "thomas.dubois@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "user-2",
    name: "Sophie Martin",
    email: "sophie.martin@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "user-3",
    name: "Lucas Bernard",
    email: "lucas.bernard@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "user-4",
    name: "Emma Petit",
    email: "emma.petit@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
  },
]

// Projets mockés
export const mockProjects: Project[] = [
  {
    id: "project-1",
    name: "Refonte Site Web",
    description: "Refonte complète du site web de l'entreprise avec nouveau design et fonctionnalités améliorées",
    startDate: "2023-01-15",
    sprintDuration: 14,
    archived: false,
    tasks: [
      {
        id: "task-1",
        title: "Analyse des besoins",
        description: "Recueillir et analyser les besoins des utilisateurs et des parties prenantes",
        status: "completed",
        assignee: mockUsers[0],
        createdAt: "2023-01-16",
        updatedAt: "2023-01-25",
        subtasks: [
          {
            id: "subtask-1-1",
            title: "Interviews utilisateurs",
            description: "Conduire des interviews avec les utilisateurs clés",
            status: "completed",
            assignee: mockUsers[0],
            createdAt: "2023-01-16",
            updatedAt: "2023-01-20",
          },
          {
            id: "subtask-1-2",
            title: "Analyse de la concurrence",
            description: "Étudier les sites web concurrents",
            status: "completed",
            assignee: mockUsers[1],
            createdAt: "2023-01-16",
            updatedAt: "2023-01-22",
          },
        ],
      },
      {
        id: "task-2",
        title: "Design UX/UI",
        description: "Créer les wireframes et maquettes du nouveau site",
        status: "completed",
        assignee: mockUsers[1],
        createdAt: "2023-01-26",
        updatedAt: "2023-02-15",
        subtasks: [
          {
            id: "subtask-2-1",
            title: "Wireframes",
            description: "Créer les wireframes pour toutes les pages",
            status: "completed",
            assignee: mockUsers[1],
            createdAt: "2023-01-26",
            updatedAt: "2023-02-05",
          },
          {
            id: "subtask-2-2",
            title: "Maquettes haute fidélité",
            description: "Créer les maquettes finales",
            status: "completed",
            assignee: mockUsers[1],
            createdAt: "2023-02-06",
            updatedAt: "2023-02-15",
          },
        ],
      },
      {
        id: "task-3",
        title: "Développement Frontend",
        description: "Implémenter les composants UI et intégrer les maquettes",
        status: "in-progress",
        assignee: mockUsers[2],
        createdAt: "2023-02-16",
        updatedAt: "2023-03-10",
        subtasks: [
          {
            id: "subtask-3-1",
            title: "Mise en place de Next.js",
            description: "Configurer le projet Next.js et les dépendances",
            status: "completed",
            assignee: mockUsers[2],
            createdAt: "2023-02-16",
            updatedAt: "2023-02-20",
          },
          {
            id: "subtask-3-2",
            title: "Composants UI",
            description: "Développer les composants UI réutilisables",
            status: "in-progress",
            assignee: mockUsers[2],
            createdAt: "2023-02-21",
            updatedAt: "2023-03-05",
          },
          {
            id: "subtask-3-3",
            title: "Intégration responsive",
            description: "Assurer la compatibilité sur tous les appareils",
            status: "todo",
            assignee: mockUsers[2],
            createdAt: "2023-03-06",
            updatedAt: "2023-03-06",
          },
        ],
      },
      {
        id: "task-4",
        title: "Développement Backend",
        description: "Implémenter les API et la logique métier",
        status: "in-progress",
        assignee: mockUsers[3],
        createdAt: "2023-02-16",
        updatedAt: "2023-03-10",
        subtasks: [
          {
            id: "subtask-4-1",
            title: "Modèles de données",
            description: "Définir les modèles et schémas de données",
            status: "completed",
            assignee: mockUsers[3],
            createdAt: "2023-02-16",
            updatedAt: "2023-02-25",
          },
          {
            id: "subtask-4-2",
            title: "API REST",
            description: "Développer les endpoints API",
            status: "in-progress",
            assignee: mockUsers[3],
            createdAt: "2023-02-26",
            updatedAt: "2023-03-10",
          },
        ],
      },
      {
        id: "task-5",
        title: "Tests et Assurance Qualité",
        description: "Tester l'application et corriger les bugs",
        status: "todo",
        assignee: mockUsers[0],
        createdAt: "2023-03-11",
        updatedAt: "2023-03-11",
        subtasks: [
          {
            id: "subtask-5-1",
            title: "Tests unitaires",
            description: "Écrire et exécuter les tests unitaires",
            status: "todo",
            assignee: mockUsers[2],
            createdAt: "2023-03-11",
            updatedAt: "2023-03-11",
          },
          {
            id: "subtask-5-2",
            title: "Tests d'intégration",
            description: "Écrire et exécuter les tests d'intégration",
            status: "todo",
            assignee: mockUsers[3],
            createdAt: "2023-03-11",
            updatedAt: "2023-03-11",
          },
          {
            id: "subtask-5-3",
            title: "Tests utilisateurs",
            description: "Organiser des sessions de test avec les utilisateurs",
            status: "todo",
            assignee: mockUsers[0],
            createdAt: "2023-03-11",
            updatedAt: "2023-03-11",
          },
        ],
      },
      {
        id: "task-6",
        title: "Déploiement",
        description: "Déployer l'application en production",
        status: "todo",
        assignee: mockUsers[3],
        createdAt: "2023-03-11",
        updatedAt: "2023-03-11",
      },
    ],
  },
  {
    id: "project-2",
    name: "Application Mobile",
    description: "Développement d'une application mobile pour les clients",
    startDate: "2023-02-01",
    sprintDuration: 7,
    archived: false,
    tasks: [
      {
        id: "task-1-p2",
        title: "Conception de l'application",
        status: "completed",
        assignee: mockUsers[1],
        createdAt: "2023-02-02",
        updatedAt: "2023-02-15",
      },
      {
        id: "task-2-p2",
        title: "Développement iOS",
        status: "in-progress",
        assignee: mockUsers[2],
        createdAt: "2023-02-16",
        updatedAt: "2023-03-01",
      },
      {
        id: "task-3-p2",
        title: "Développement Android",
        status: "in-progress",
        assignee: mockUsers[3],
        createdAt: "2023-02-16",
        updatedAt: "2023-03-01",
      },
      {
        id: "task-4-p2",
        title: "Tests et déploiement",
        status: "todo",
        assignee: mockUsers[0],
        createdAt: "2023-03-02",
        updatedAt: "2023-03-02",
      },
    ],
  },
  {
    id: "project-3",
    name: "Système de Gestion Interne",
    description: "Mise à jour du système de gestion interne de l'entreprise",
    startDate: "2022-10-15",
    sprintDuration: 14,
    archived: true,
    tasks: [
      {
        id: "task-1-p3",
        title: "Analyse des besoins",
        status: "completed",
        assignee: mockUsers[0],
        createdAt: "2022-10-16",
        updatedAt: "2022-10-30",
      },
      {
        id: "task-2-p3",
        title: "Développement du système",
        status: "completed",
        assignee: mockUsers[2],
        createdAt: "2022-11-01",
        updatedAt: "2022-12-15",
      },
      {
        id: "task-3-p3",
        title: "Tests et déploiement",
        status: "completed",
        assignee: mockUsers[3],
        createdAt: "2022-12-16",
        updatedAt: "2023-01-15",
      },
    ],
  },
]
